main:
  - name: Project
    url: /
    weight: 10
  - name: Science
    url: /science/
    weight: 20
  - name: Technology
    url: /technology/
    weight: 30
  - name: Use Cases
    url: /use-cases/
    weight: 40
  - name: News
    url: /news/
    weight: 50
  - name: Consortium
    url: /consortium/
    weight: 60
